### ISSUE TITLE
apply in reduce

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingguide#46]
Apparently, it was possible to use apply in reduce:

```python
reduce(apply, [func1, func2, func3], initial_value)
```

This essentially produces:

```python
func3(func2(func1(initial_value)))
```

The advice we give in https://portingguide.readthedocs.io/en/latest/builtins.html?highlight=apply#removed-apply doesn't cover such cases.

I think it should mention that if you used `apply` as an argument to other functions, such as `reduce`, you should replace it with an equivalent `lambda` (such as `lambda x, y: y(x)` in the reduce case), or refactor the code not to do that.

See also (in Czech) https://twitter.com/Glutexo/status/1049957406917169153

cc @glutexo

**Comment by Glutexo** [comment]
Just to clarify, since I didn’t bother to test on a Python version with _apply_: I blindly trusted [this comment](
https://stackoverflow.com/questions/17122644/compute-a-chain-of-functions-in-python#comment24778695_17122666) on Stack Overflow explaining how to redefine it. If that guy was wrong, then I was too.

**Comment by hroncok** [comment]
Hmm, it might not work at all. Sorry for the noise.
