### ISSUE TITLE
Article on StandardError is inaccurate

### ISSUE THREAD

**Issue by he-lo-art** [fedora-python/portingguide#66]
Thank you for your article. Respectfully I would like to express my disagreement with the section on the StandardError.

> It was the base class for built-in exceptions

This is not correct. The base class was also BaseException, the base class for non-exit-causing-intented exceptions was also Exception, and the base class for actual errors was StandardError. See also: [https://docs.python.org/2.7/library/exceptions.html#exception-hierarchy](https://docs.python.org/2.7/library/exceptions.html#exception-hierarchy)

> it proved to be an unnecessary link in almost any exception’s inheritance chain

Is this true? Since ages I am trying to do proper error handling in my Python-based executables, and that involves distinguishing errors from non-errors, and logic errors (a.k.a. bugs) from non-logic errors.

To support the former, I wrote the following function:
```
def is_standard_error(exc):
    return isinstance(exc, Exception) \
        and not( isinstance(exc, Warning) ) \
        and not( isinstance(exc, StopIteration) ) \
        and not( isinstance(exc, StopAsyncIteration) )
```

I consider the removal as unfortunate, as my replacement function has to know all other cases, which violates the rule of centralization of knowledge. I guess there was a lack of understanding by the majority of users, and unfortunately the Python creators reacted to that by removing a feature. StandardError was a standardized way by which errors could be distinguished from other exceptions.

**Comment by encukou** [comment]
>>  It was the base class for built-in exceptions
>
> This is not correct.

Right, it would be more correct to replace "the" with "a": `It was a base class for built-in exceptions.` Would that work for you?

>> it proved to be an unnecessary link in almost any exception’s inheritance chain
>
> Is this true?

I believe that by the time you need to distinguish between `StandardError` and `Exception`, the difference between logic errors and non-logic errors is not relevant, because unhandled non-logic errors are bugs.
But I don't fully understand what you mean by logic vs. non-logic errors. What's your `is_standard_error` function used for?


> I consider the removal as unfortunate

Unfortunately, an issue and discussion here is very unlikely to influence a decision in Python.

**Comment by encukou** [comment]
I'll close the issue. If you have more to discuss, let's reopen.
